// 命理散文翻譯（en / ja）
//
// 這裡只收「專案自撰」的斷語散文，共 28 條。刻意不收的有兩類：
//
// 1. **《周易》爻辭原典（384 條）**——`yaoReading.ts` 的 VERIFIED_YAO_TEXTS
//    是逐條依維基文庫校對的經文。翻譯經文是另一種工作（Wilhelm、Legge、Lynn
//    各成一本書），不是這個 App 該自己動手的事，也不該讓機器翻。原文照舊呈現。
// 2. **資料值字面量（148 條）**——五行、六親、吉凶等級、卦名。它們是存進記錄
//    裡、會被比對的資料值，不是給人讀的句子（見 i18nCoverage 的 DATA_VALUE_PATTERNS）。
//
// 術語處理原則：**六親與卦理術語一律保留漢字，只翻連接文，並在首次出現時加註**。
// 理由是這些詞在畫面上另有出處——六爻盤那一列就直接寫著「妻財」「世爻」。
// 若斷語寫 Wealth 而盤上寫妻財，使用者無法把兩者對起來，反而比不翻更難懂。

import type { Lang } from '@/services/i18n';

export const divinationProse: Record<string, Partial<Record<Lang, string>>> = {
  // ── 動爻位置指引（yaoReading）──
  // 這六組是純白話行動建議，術語只有初爻／內卦這類位置名，直譯即可。

  'yao.pos1.plain': {
    en: 'The first line is where a matter has only just begun. Reading the situation and keeping your resources intact matters more than declaring a position or placing a bet.',
    ja: '初爻は物事が始まったばかりの位置です。まず状況を見極め、力を温存することが、すぐに態度を示したり賭けに出たりするより重要です。',
  },
  'yao.pos1.action': {
    en: 'Finish one low-risk preparation today: gather information, list your conditions, or sleep on the next step before deciding.',
    ja: '今日は低リスクな準備を一つ済ませましょう。情報を集める、条件を書き出す、あるいは次の一手を一晩寝かせてから決める。',
  },

  'yao.pos2.plain': {
    en: 'The second line sits at the centre of the inner trigram. The point is to make the foundation solid, and to let people you trust see what you need and what you can do.',
    ja: '二爻は内卦の中央にあります。基礎を固め、信頼できる人にあなたの必要と能力を見せることが要点です。',
  },
  'yao.pos2.action': {
    en: 'Check your direction with someone who gives concrete feedback; put terms, timing and responsibilities in writing.',
    ja: '実際的なフィードバックをくれる人に方向性を確認し、協力条件・期間・責任を書面で明確にしましょう。',
  },

  'yao.pos3.plain': {
    en: 'The third line stands on the border between inner and outer, the easiest place to lose balance by rushing across. Diligence is fine, but stay alert.',
    ja: '三爻は内と外の境目にあり、急いで越えようとして均衡を崩しやすい位置です。勤勉であってよいが、警戒は保つこと。',
  },
  'yao.pos3.action': {
    en: 'Split the big move into two steps and run a reversible small test first; set a stop-loss point at the same time.',
    ja: '大きな動きを二段階に分け、まず引き返せる小さな試行を。同時に損切りラインを決めておきましょう。',
  },

  'yao.pos4.plain': {
    en: 'The fourth line enters the outer trigram, a turning point between advancing and withdrawing. Trying is fine; mistaking a probe for a settled outcome is not.',
    ja: '四爻は外卦に入り、進退の転換点です。試みてよいが、探りを決着と取り違えないこと。',
  },
  'yao.pos4.action': {
    en: 'Replace full commitment with a small-scale trial; expand only once the key signal is clear.',
    ja: '全面投入の代わりに小規模な試行を。重要なシグナルが明確になってから広げましょう。',
  },

  'yao.pos5.plain': {
    en: 'The fifth line holds the honoured, centred position, suited to consolidating resources, taking responsibility openly and setting the main line. Keep the decision open to scrutiny.',
    ja: '五爻は尊位にあり中を得ています。資源をまとめ、公に責任を引き受け、主軸を定めるのに適した位置です。ただし決定は検証可能にしておくこと。',
  },
  'yao.pos5.action': {
    en: 'Once the goal is set, name one owner and one deadline, and invite someone who covers your blind spots.',
    ja: '目標を確認したら、主担当と期限を一つずつ決め、死角を補える人を自分から誘いましょう。',
  },

  'yao.pos6.plain': {
    en: 'The top line reaches the extreme of the matter. Results can be wrapped up, but adding more easily turns an advantage into excess.',
    ja: '上爻は物事の極みに至ります。成果はまとめられますが、さらに積み増せば優位が行き過ぎに転じやすい。',
  },
  'yao.pos6.action': {
    en: 'Finish the wrap-up, settle accounts and hand over; pause new commitments and leave room to review the next round.',
    ja: 'まず締めくくり・清算・引き継ぎを終えること。新たな約束は止め、次の方向を見直す余地を残しましょう。',
  },

  // ── 體用斷語補述（yaoReading 的 verdictNote）──
  // 開頭的空格是刻意的：這段是接在 plainLanguage 後面的補述。

  'yao.verdict.good': {
    en: ' 體用 (body and use) and the seasonal timing lean towards advancing; even so, confirm in stages rather than committing everything at once.',
    ja: ' 體用と時令はやや前進を支持します。それでも一度に賭けきらず、段階的に確認を。',
  },
  'yao.verdict.bad': {
    en: ' 體用 conditions are tight; make this step about defending, cutting cost and keeping your options open.',
    ja: ' 體用の条件は厳しめです。この一手は守り・コスト削減・選択肢の確保を優先に。',
  },
  'yao.verdict.neutral': {
    en: ' Conditions have not settled yet; use reversible actions to gather more signal first.',
    ja: ' 条件はまだ定まっていません。まず引き返せる行動でシグナルを集めましょう。',
  },

  // ── 體卦旺衰（liuyao 的 STRENGTH_TEXT）──
  // 體卦、令氣、旺相休囚死都是卦理術語，保留漢字並在英文首見處加註。

  'liuyao.strength.wang': {
    en: '體卦 (the body trigram) rules the season and is 旺 (thriving): your own force is full, so a favourable verdict lands more solidly and an unfavourable one can still be borne.',
    ja: '體卦が令を得て旺。自身の気が満ちており、吉はより確かに、凶も耐えられます。',
  },
  'liuyao.strength.xiang': {
    en: '體卦 is generated by the seasonal force and is 相 (waxing): the timing helps you, and momentum is still building.',
    ja: '體卦が令気に生じられて相。時の助けを得て、勢いを蓄えている段階です。',
  },
  'liuyao.strength.xiu': {
    en: '體卦 generates the seasonal force and is 休 (resting): effort leaks outward and strength is ordinary, so hold what you have rather than expand.',
    ja: '體卦が令気を生じて休。力が外に漏れ、勢いは平凡。守成に努め、拡張は控えましょう。',
  },
  'liuyao.strength.qiu': {
    en: '體卦 restrains the seasonal force and is 囚 (trapped): moving against the timing, blocked at every turn, much effort for little effect.',
    ja: '體卦が令気を剋して囚。時に逆らって動くため各所で阻まれ、労多くして功少なし。',
  },
  'liuyao.strength.si': {
    en: '體卦 is restrained by the seasonal force and is 死 (dormant), at its weakest. Do not push for results now; wait for the timing to turn.',
    ja: '體卦が令気に剋されて死。最も力がなく、今は自ら成果を求めず、時の転換を静かに待つとき。',
  },

  // ── 用神取法說明（useGod）──
  // 六親名稱一律保留，英文首見加註一次。這些字在六爻盤上就直接印著，
  // 譯成 Wealth／Authority 反而讓斷語與盤面對不起來。

  'useGod.wealth': {
    en: 'For wealth questions, 妻財 (Wife-Wealth, the wealth relation) is the candidate 用神 (governing line); read its position in the primary hexagram and its timing. 兄弟 (Sibling) drains wealth, 子孫 (Offspring) generates it.',
    ja: '金運の占では「妻財」を用神の候補とし、本卦での位置と時期条件を見ます。兄弟は財を劫し、子孫は財を生じます。',
  },
  'useGod.career': {
    en: 'For career questions, 官鬼 (Officer-Ghost, the authority relation) is the candidate 用神; read duties, position and external rules. 父母 (Parent) as documents and seals is favourable; 子孫 (Offspring) restraining 官鬼 is not.',
    ja: '仕事の占では「官鬼」を用神の候補とし、職責・地位・外的な規範の条件を見ます。父母は文書・印信として喜ばれ、子孫が官を剋するのは忌みます。',
  },
  'useGod.study': {
    en: 'For study and certification questions, 父母 (Parent, the document relation) is the candidate 用神; read materials, teachers and paperwork. 官鬼 generating the documents is favourable; 妻財 restraining 父母 is not.',
    ja: '学業・資格の占では「父母」を用神の候補とし、資料・師長・文書の条件を見ます。官鬼が文書を生じるのは喜び、妻財が父母を剋するのは忌みます。',
  },
  'useGod.health': {
    en: 'For illness questions, 世爻 (the Self line) is the 用神 — when you divine for yourself, 世爻 is you. 官鬼 signifies the ailment, 子孫 the medicine that resolves it.',
    ja: '病の占では「世爻」を用神とします（自占では世爻が本人）。官鬼は病症の象、子孫は医薬・解神です。',
  },
  'useGod.travel': {
    en: 'For travel questions, 世爻 (the Self line) is the 用神 — when you divine for yourself, 世爻 is the traveller. 父母 stands for vehicles and the itinerary, 兄弟 for obstruction and loss.',
    ja: '旅行の占では「世爻」を用神とします（自占では世爻が旅する本人）。父母は舟車・行程、兄弟は阻隔と消耗の神です。',
  },
  'useGod.loveMale': {
    en: 'For relationship questions asked by a man, 妻財 (Wife-Wealth) is the 用神, the person sought. 兄弟 (Sibling) competing and seizing is unfavourable; 子孫 (Offspring) generating 妻財 is favourable.',
    ja: '恋愛の占で男性が占う場合、「妻財」を用神（求める相手）とします。兄弟の争奪は忌み、子孫が財を生じるのを喜びます。',
  },
  'useGod.loveFemale': {
    en: 'For relationship questions asked by a woman, 官鬼 (Officer-Ghost) is the 用神, the person sought. 子孫 (Offspring) restraining 官鬼 is unfavourable; 妻財 (Wife-Wealth) generating it is favourable.',
    ja: '恋愛の占で女性が占う場合、「官鬼」を用神（求める相手）とします。子孫が官を剋するのは忌み、妻財が官を生じるのを喜びます。',
  },

  // ── 文王卦逐條理由（wenwang）──
  // 這些是「用神斷語」下方那份逐條加權的理由。原文以樣板字串組出，
  // 譯文用 {name} 佔位符對應；六親、地支、五行一律以參數帶入漢字原值，
  // 因為同一份斷語旁邊的納甲盤就印著這些字。

  'wenwang.selfSubject': {
    en: 'Divining for yourself, 世爻 (the Self line) is the 用神: 世 sits on line {pos}, {sb} ({rel} holds 世).',
    ja: '自占では世爻を用神とします。世は{pos}爻{sb}（{rel}持世）にあります。',
  },
  'wenwang.monthState': {
    en: 'Month branch {month} puts {season} in power; the 用神 is {element}, hence 「{state}」.',
    ja: '月建{month}により{season}が当権。用神は{element}で「{state}」。',
  },
  'wenwang.dayBranch': {
    en: 'Day pillar {day}: {rel}',
    ja: '日建{day}：{rel}',
  },
  'wenwang.void': {
    en: '用神 {branch} falls into the {xun} 空亡 (void).',
    ja: '用神{branch}は{xun}の空亡に落ちます。',
  },
  'wenwang.monthBroken': {
    en: '用神 {branch} is clashed by month branch {month} — 月破 (month-broken).',
    ja: '用神{branch}は月建{month}に沖され、月破となります。',
  },
  'wenwang.hidden': {
    en: '用神 is absent from the hexagram, hidden beneath line {pos} ({flying}) — {rel}.',
    ja: '用神は卦に現れず、{pos}爻{flying}の下に伏します（{rel}）。',
  },
  'wenwang.tabooHoldsSelf': {
    en: '{taboo} holds 世 — the trouble asked about clings to you.',
    ja: '{taboo}が持世。問うところの患いが身にまといます。',
  },
  'wenwang.favorableHoldsSelf': {
    en: '{fav} holds 世 — the helping influence is on your own side.',
    ja: '{fav}が持世。事を助ける神が自分にあります。',
  },
  'wenwang.darkGenerates': {
    en: 'Line {pos} {rel} {sb} is clashed by the day branch and stirs covertly (暗動), generating the 用神.',
    ja: '{pos}爻{rel}{sb}が日辰に沖されて暗動し、用神を生じます。',
  },
  'wenwang.darkRestrains': {
    en: 'Line {pos} {rel} {sb} is clashed by the day branch and stirs covertly (暗動), restraining the 用神.',
    ja: '{pos}爻{rel}{sb}が日辰に沖されて暗動し、用神を剋します。',
  },
  'wenwang.moverGenerates': {
    en: 'Line {line} {rel} {sb} moves and generates the 用神.',
    ja: '{line}爻{rel}{sb}が動いて用神を生じます。',
  },
  'wenwang.moverRestrains': {
    en: 'Line {line} {rel} {sb} moves and restrains the 用神.',
    ja: '{line}爻{rel}{sb}が動いて用神を剋します。',
  },
  'wenwang.tabooMoves': {
    en: 'Line {line} {taboo} is in motion — the adverse influence for this question.',
    ja: '{line}爻{taboo}が発動。問うところの忌神です。',
  },
  'wenwang.favorableMoves': {
    en: 'Line {line} {fav} is in motion — the favourable influence for this question.',
    ja: '{line}爻{fav}が発動。問うところの喜神です。',
  },
  'wenwang.backGenerate': {
    en: 'The 用神 moves and transforms into {sb}, which generates it back (回頭生).',
    ja: '用神が発動して{sb}に化し、回頭生となります。',
  },
  'wenwang.backRestrain': {
    en: 'The 用神 moves and transforms into {sb}, which restrains it back (回頭剋).',
    ja: '用神が発動して{sb}に化し、回頭剋となります。',
  },
  'wenwang.advancing': {
    en: '用神 {branch} transforms into {to} — 進神 (advancing).',
    ja: '用神{branch}が{to}に化し、進神となります。',
  },
  'wenwang.retreating': {
    en: '用神 {branch} transforms into {to} — 退神 (retreating).',
    ja: '用神{branch}が{to}に化し、退神となります。',
  },
  'wenwang.triadJoin': {
    en: '{where} forms{source}; the 用神 sits inside the triad and gains its support.',
    ja: '{where}が成立{source}。用神が局中にあり助けを得ます。',
  },
  'wenwang.triadGenerates': {
    en: '{where} forms{source}; the triad generates the 用神.',
    ja: '{where}が成立{source}。局が用神を生じます。',
  },
  'wenwang.triadRestrains': {
    en: '{where} forms{source}; the triad restrains the 用神.',
    ja: '{where}が成立{source}。局が用神を剋します。',
  },
  'wenwang.triadDrains': {
    en: '{where} forms{source}; the 用神 sits inside the triad but drains into it.',
    ja: '{where}が成立{source}。用神は局中にありながら気を洩らします。',
  },
  'wenwang.dualMoving': {
    en: '用神 {subject} appears twice; line {line} is the moving line, so it is taken as primary.',
    ja: '用神{subject}が両現。{line}爻が動爻のため、これを主とします。',
  },
  'wenwang.dualPick': {
    en: '用神 {subject} appears twice; line {pos} is taken as primary.',
    ja: '用神{subject}が両現。{pos}爻を主とします。',
  },

  // ── 體用生剋斷語（liuyao）──

  'liuyao.bodyUse.harmony': {
    en: 'Body and use are both {body} — 體用比和 (in accord). The matter aligns with your own intent; things move smoothly without effort spent on manoeuvring.',
    ja: '體用ともに{body}で比和。事と己の意が合い、順調に進み、無理な立ち回りは要りません。',
  },
  'liuyao.bodyUse.useFeedsBody': {
    en: '{use} generates {body} — 用生體. Outside forces come to help and benefactors support you; the most favourable sign. Take the momentum as it comes.',
    ja: '{use}が{body}を生じ、用生体。外力の助けと貴人の引き立てを得られる最も有利な象。勢いに乗って受けとめましょう。',
  },
  'liuyao.bodyUse.bodyOvercomesUse': {
    en: '{body} restrains {use} — 體剋用. The situation is yours to control; it takes effort, but you can see it through to a harvest.',
    ja: '{body}が{use}を剋し、体剋用。局面は自分の手中にあり、労は要るが最後は掌握して収穫できます。',
  },
  'liuyao.bodyUse.bodyFeedsUse': {
    en: '{body} generates {use} — 體生用. Your energy drains outward: much given, little returned. Leave yourself room and do not over-commit.',
    ja: '{body}が{use}を生じ、体生用。心力が外に漏れ、与える割に戻りが少ない。余地を残し、投入しすぎないこと。',
  },
  'liuyao.bodyUse.useOvercomesBody': {
    en: '{use} restrains {body} — 用剋體. Outside pressure exceeds your own force; forcing it now will only meet setbacks. Withdraw and wait for the timing.',
    ja: '{use}が{body}を剋し、用剋体。外圧が己身を上回り、今強いれば必ず挫かれます。退いて時を待ちましょう。',
  },

  // ── 文王卦（wenwang）──

  'wenwang.noUseGod': {
    en: '用神 does not appear in the hexagram and no 伏神 (hidden line) can be drawn on',
    ja: '用神が卦に現れず、伏神も取れません',
  },
};
