// 命理散文翻譯（en / ja）
//
// 這裡只收「專案自撰」的斷語散文（目前 57 條，下限由 divinationProse.test.ts 守）。
// 刻意不收的有兩類：
//
// 1. **《周易》爻辭原典（384 條）**——`yaoReading.ts` 的 VERIFIED_YAO_TEXTS
//    是逐條依維基文庫校對的經文。翻譯經文是另一種工作（Wilhelm、Legge、Lynn
//    各成一本書），不是這個 App 該自己動手的事，也不該讓機器翻。原文照舊呈現。
// 2. **資料值字面量（148 條）**——五行、六親、吉凶等級、卦名。它們是存進記錄
//    裡、會被比對的資料值，不是給人讀的句子（見 i18nCoverage 的 DATA_VALUE_PATTERNS）。
//
// 術語處理原則：**六親與卦理術語一律保留漢字，只翻連接文，並在首次出現時加註**。
// 理由是這些詞在畫面上另有出處——六爻盤那一列就直接寫著「妻財」「世爻」。
// 若斷語寫 Wealth 而盤上寫妻財，使用者無法把兩者對起來，反而比不翻更難懂。

import type { Lang } from '@/services/i18n';

export const divinationProse: Record<string, Partial<Record<Lang, string>>> = {
  // ── 動爻位置指引（yaoReading）──
  // 這六組是純白話行動建議，術語只有初爻／內卦這類位置名，直譯即可。

  'yao.pos1.plain': {
    en: 'The first line is where a matter has only just begun. Reading the situation and keeping your resources intact matters more than declaring a position or placing a bet.',
    ja: '初爻は物事が始まったばかりの位置です。まず状況を見極め、力を温存することが、すぐに態度を示したり賭けに出たりするより重要です。',
  },
  'yao.pos1.action': {
    en: 'Finish one low-risk preparation today: gather information, list your conditions, or sleep on the next step before deciding.',
    ja: '今日は低リスクな準備を一つ済ませましょう。情報を集める、条件を書き出す、あるいは次の一手を一晩寝かせてから決める。',
  },

  'yao.pos2.plain': {
    en: 'The second line sits at the centre of the inner trigram. The point is to make the foundation solid, and to let people you trust see what you need and what you can do.',
    ja: '二爻は内卦の中央にあります。基礎を固め、信頼できる人にあなたの必要と能力を見せることが要点です。',
  },
  'yao.pos2.action': {
    en: 'Check your direction with someone who gives concrete feedback; put terms, timing and responsibilities in writing.',
    ja: '実際的なフィードバックをくれる人に方向性を確認し、協力条件・期間・責任を書面で明確にしましょう。',
  },

  'yao.pos3.plain': {
    en: 'The third line stands on the border between inner and outer, the easiest place to lose balance by rushing across. Diligence is fine, but stay alert.',
    ja: '三爻は内と外の境目にあり、急いで越えようとして均衡を崩しやすい位置です。勤勉であってよいが、警戒は保つこと。',
  },
  'yao.pos3.action': {
    en: 'Split the big move into two steps and run a reversible small test first; set a stop-loss point at the same time.',
    ja: '大きな動きを二段階に分け、まず引き返せる小さな試行を。同時に損切りラインを決めておきましょう。',
  },

  'yao.pos4.plain': {
    en: 'The fourth line enters the outer trigram, a turning point between advancing and withdrawing. Trying is fine; mistaking a probe for a settled outcome is not.',
    ja: '四爻は外卦に入り、進退の転換点です。試みてよいが、探りを決着と取り違えないこと。',
  },
  'yao.pos4.action': {
    en: 'Replace full commitment with a small-scale trial; expand only once the key signal is clear.',
    ja: '全面投入の代わりに小規模な試行を。重要なシグナルが明確になってから広げましょう。',
  },

  'yao.pos5.plain': {
    en: 'The fifth line holds the honoured, centred position, suited to consolidating resources, taking responsibility openly and setting the main line. Keep the decision open to scrutiny.',
    ja: '五爻は尊位にあり中を得ています。資源をまとめ、公に責任を引き受け、主軸を定めるのに適した位置です。ただし決定は検証可能にしておくこと。',
  },
  'yao.pos5.action': {
    en: 'Once the goal is set, name one owner and one deadline, and invite someone who covers your blind spots.',
    ja: '目標を確認したら、主担当と期限を一つずつ決め、死角を補える人を自分から誘いましょう。',
  },

  'yao.pos6.plain': {
    en: 'The top line reaches the extreme of the matter. Results can be wrapped up, but adding more easily turns an advantage into excess.',
    ja: '上爻は物事の極みに至ります。成果はまとめられますが、さらに積み増せば優位が行き過ぎに転じやすい。',
  },
  'yao.pos6.action': {
    en: 'Finish the wrap-up, settle accounts and hand over; pause new commitments and leave room to review the next round.',
    ja: 'まず締めくくり・清算・引き継ぎを終えること。新たな約束は止め、次の方向を見直す余地を残しましょう。',
  },

  // ── 體用斷語補述（yaoReading 的 verdictNote）──
  // 開頭的空格是刻意的：這段是接在 plainLanguage 後面的補述。

  'yao.verdict.good': {
    en: ' 體用 (body and use) and the seasonal timing lean towards advancing; even so, confirm in stages rather than committing everything at once.',
    ja: ' 體用と時令はやや前進を支持します。それでも一度に賭けきらず、段階的に確認を。',
  },
  'yao.verdict.bad': {
    en: ' 體用 conditions are tight; make this step about defending, cutting cost and keeping your options open.',
    ja: ' 體用の条件は厳しめです。この一手は守り・コスト削減・選択肢の確保を優先に。',
  },
  'yao.verdict.neutral': {
    en: ' Conditions have not settled yet; use reversible actions to gather more signal first.',
    ja: ' 条件はまだ定まっていません。まず引き返せる行動でシグナルを集めましょう。',
  },

  // ── 體卦旺衰（liuyao 的 STRENGTH_TEXT）──
  // 體卦、令氣、旺相休囚死都是卦理術語，保留漢字並在英文首見處加註。

  'liuyao.strength.wang': {
    en: '體卦 (the body trigram) rules the season and is 旺 (thriving): your own force is full, so a favourable verdict lands more solidly and an unfavourable one can still be borne.',
    ja: '體卦が令を得て旺。自身の気が満ちており、吉はより確かに、凶も耐えられます。',
  },
  'liuyao.strength.xiang': {
    en: '體卦 is generated by the seasonal force and is 相 (waxing): the timing helps you, and momentum is still building.',
    ja: '體卦が令気に生じられて相。時の助けを得て、勢いを蓄えている段階です。',
  },
  'liuyao.strength.xiu': {
    en: '體卦 generates the seasonal force and is 休 (resting): effort leaks outward and strength is ordinary, so hold what you have rather than expand.',
    ja: '體卦が令気を生じて休。力が外に漏れ、勢いは平凡。守成に努め、拡張は控えましょう。',
  },
  'liuyao.strength.qiu': {
    en: '體卦 restrains the seasonal force and is 囚 (trapped): moving against the timing, blocked at every turn, much effort for little effect.',
    ja: '體卦が令気を剋して囚。時に逆らって動くため各所で阻まれ、労多くして功少なし。',
  },
  'liuyao.strength.si': {
    en: '體卦 is restrained by the seasonal force and is 死 (dormant), at its weakest. Do not push for results now; wait for the timing to turn.',
    ja: '體卦が令気に剋されて死。最も力がなく、今は自ら成果を求めず、時の転換を静かに待つとき。',
  },

  // ── 用神取法說明（useGod）──
  // 六親名稱一律保留，英文首見加註一次。這些字在六爻盤上就直接印著，
  // 譯成 Wealth／Authority 反而讓斷語與盤面對不起來。

  'useGod.wealth': {
    en: 'For wealth questions, 妻財 (Wife-Wealth, the wealth relation) is the candidate 用神 (governing line); read its position in the primary hexagram and its timing. 兄弟 (Sibling) drains wealth, 子孫 (Offspring) generates it.',
    ja: '金運の占では「妻財」を用神の候補とし、本卦での位置と時期条件を見ます。兄弟は財を劫し、子孫は財を生じます。',
  },
  'useGod.career': {
    en: 'For career questions, 官鬼 (Officer-Ghost, the authority relation) is the candidate 用神; read duties, position and external rules. 父母 (Parent) as documents and seals is favourable; 子孫 (Offspring) restraining 官鬼 is not.',
    ja: '仕事の占では「官鬼」を用神の候補とし、職責・地位・外的な規範の条件を見ます。父母は文書・印信として喜ばれ、子孫が官を剋するのは忌みます。',
  },
  'useGod.study': {
    en: 'For study and certification questions, 父母 (Parent, the document relation) is the candidate 用神; read materials, teachers and paperwork. 官鬼 generating the documents is favourable; 妻財 restraining 父母 is not.',
    ja: '学業・資格の占では「父母」を用神の候補とし、資料・師長・文書の条件を見ます。官鬼が文書を生じるのは喜び、妻財が父母を剋するのは忌みます。',
  },
  'useGod.health': {
    en: 'For illness questions, 世爻 (the Self line) is the 用神 — when you divine for yourself, 世爻 is you. 官鬼 signifies the ailment, 子孫 the medicine that resolves it.',
    ja: '病の占では「世爻」を用神とします（自占では世爻が本人）。官鬼は病症の象、子孫は医薬・解神です。',
  },
  'useGod.travel': {
    en: 'For travel questions, 世爻 (the Self line) is the 用神 — when you divine for yourself, 世爻 is the traveller. 父母 stands for vehicles and the itinerary, 兄弟 for obstruction and loss.',
    ja: '旅行の占では「世爻」を用神とします（自占では世爻が旅する本人）。父母は舟車・行程、兄弟は阻隔と消耗の神です。',
  },
  'useGod.loveMale': {
    en: 'For relationship questions asked by a man, 妻財 (Wife-Wealth) is the 用神, the person sought. 兄弟 (Sibling) competing and seizing is unfavourable; 子孫 (Offspring) generating 妻財 is favourable.',
    ja: '恋愛の占で男性が占う場合、「妻財」を用神（求める相手）とします。兄弟の争奪は忌み、子孫が財を生じるのを喜びます。',
  },
  'useGod.loveFemale': {
    en: 'For relationship questions asked by a woman, 官鬼 (Officer-Ghost) is the 用神, the person sought. 子孫 (Offspring) restraining 官鬼 is unfavourable; 妻財 (Wife-Wealth) generating it is favourable.',
    ja: '恋愛の占で女性が占う場合、「官鬼」を用神（求める相手）とします。子孫が官を剋するのは忌み、妻財が官を生じるのを喜びます。',
  },

  // ── 文王卦逐條理由（wenwang）──
  // 這些是「用神斷語」下方那份逐條加權的理由。原文以樣板字串組出，
  // 譯文用 {name} 佔位符對應；六親、地支、五行一律以參數帶入漢字原值，
  // 因為同一份斷語旁邊的納甲盤就印著這些字。

  'wenwang.selfSubject': {
    en: 'Divining for yourself, 世爻 (the Self line) is the 用神: 世 sits on line {pos}, {sb} ({rel} holds 世).',
    ja: '自占では世爻を用神とします。世は{pos}爻{sb}（{rel}持世）にあります。',
  },
  'wenwang.monthState': {
    en: 'Month branch {month} puts {season} in power; the 用神 is {element}, hence 「{state}」.',
    ja: '月建{month}により{season}が当権。用神は{element}で「{state}」。',
  },
  'wenwang.dayBranch': {
    en: 'Day pillar {day}: {rel}',
    ja: '日建{day}：{rel}',
  },
  'wenwang.void': {
    en: '用神 {branch} falls into the {xun} 空亡 (void).',
    ja: '用神{branch}は{xun}の空亡に落ちます。',
  },
  'wenwang.monthBroken': {
    en: '用神 {branch} is clashed by month branch {month} — 月破 (month-broken).',
    ja: '用神{branch}は月建{month}に沖され、月破となります。',
  },
  'wenwang.hidden': {
    en: '用神 is absent from the hexagram, hidden beneath line {pos} ({flying}) — {rel}.',
    ja: '用神は卦に現れず、{pos}爻{flying}の下に伏します（{rel}）。',
  },
  'wenwang.tabooHoldsSelf': {
    en: '{taboo} holds 世 — the trouble asked about clings to you.',
    ja: '{taboo}が持世。問うところの患いが身にまといます。',
  },
  'wenwang.favorableHoldsSelf': {
    en: '{fav} holds 世 — the helping influence is on your own side.',
    ja: '{fav}が持世。事を助ける神が自分にあります。',
  },
  'wenwang.darkGenerates': {
    en: 'Line {pos} {rel} {sb} is clashed by the day branch and stirs covertly (暗動), generating the 用神.',
    ja: '{pos}爻{rel}{sb}が日辰に沖されて暗動し、用神を生じます。',
  },
  'wenwang.darkRestrains': {
    en: 'Line {pos} {rel} {sb} is clashed by the day branch and stirs covertly (暗動), restraining the 用神.',
    ja: '{pos}爻{rel}{sb}が日辰に沖されて暗動し、用神を剋します。',
  },
  'wenwang.moverGenerates': {
    en: 'Line {line} {rel} {sb} moves and generates the 用神.',
    ja: '{line}爻{rel}{sb}が動いて用神を生じます。',
  },
  'wenwang.moverRestrains': {
    en: 'Line {line} {rel} {sb} moves and restrains the 用神.',
    ja: '{line}爻{rel}{sb}が動いて用神を剋します。',
  },
  'wenwang.tabooMoves': {
    en: 'Line {line} {taboo} is in motion — the adverse influence for this question.',
    ja: '{line}爻{taboo}が発動。問うところの忌神です。',
  },
  'wenwang.favorableMoves': {
    en: 'Line {line} {fav} is in motion — the favourable influence for this question.',
    ja: '{line}爻{fav}が発動。問うところの喜神です。',
  },
  'wenwang.backGenerate': {
    en: 'The 用神 moves and transforms into {sb}, which generates it back (回頭生).',
    ja: '用神が発動して{sb}に化し、回頭生となります。',
  },
  'wenwang.backRestrain': {
    en: 'The 用神 moves and transforms into {sb}, which restrains it back (回頭剋).',
    ja: '用神が発動して{sb}に化し、回頭剋となります。',
  },
  'wenwang.advancing': {
    en: '用神 {branch} transforms into {to} — 進神 (advancing).',
    ja: '用神{branch}が{to}に化し、進神となります。',
  },
  'wenwang.retreating': {
    en: '用神 {branch} transforms into {to} — 退神 (retreating).',
    ja: '用神{branch}が{to}に化し、退神となります。',
  },
  'wenwang.triadJoin': {
    en: '{where} forms{source}; the 用神 sits inside the triad and gains its support.',
    ja: '{where}が成立{source}。用神が局中にあり助けを得ます。',
  },
  'wenwang.triadGenerates': {
    en: '{where} forms{source}; the triad generates the 用神.',
    ja: '{where}が成立{source}。局が用神を生じます。',
  },
  'wenwang.triadRestrains': {
    en: '{where} forms{source}; the triad restrains the 用神.',
    ja: '{where}が成立{source}。局が用神を剋します。',
  },
  'wenwang.triadDrains': {
    en: '{where} forms{source}; the 用神 sits inside the triad but drains into it.',
    ja: '{where}が成立{source}。用神は局中にありながら気を洩らします。',
  },
  'wenwang.dualMoving': {
    en: '用神 {subject} appears twice; line {line} is the moving line, so it is taken as primary.',
    ja: '用神{subject}が両現。{line}爻が動爻のため、これを主とします。',
  },
  'wenwang.dualPick': {
    en: '用神 {subject} appears twice; line {pos} is taken as primary.',
    ja: '用神{subject}が両現。{pos}爻を主とします。',
  },

  // ── 體用生剋斷語（liuyao）──

  'liuyao.bodyUse.harmony': {
    en: 'Body and use are both {body} — 體用比和 (in accord). The matter aligns with your own intent; things move smoothly without effort spent on manoeuvring.',
    ja: '體用ともに{body}で比和。事と己の意が合い、順調に進み、無理な立ち回りは要りません。',
  },
  'liuyao.bodyUse.useFeedsBody': {
    en: '{use} generates {body} — 用生體. Outside forces come to help and benefactors support you; the most favourable sign. Take the momentum as it comes.',
    ja: '{use}が{body}を生じ、用生体。外力の助けと貴人の引き立てを得られる最も有利な象。勢いに乗って受けとめましょう。',
  },
  'liuyao.bodyUse.bodyOvercomesUse': {
    en: '{body} restrains {use} — 體剋用. The situation is yours to control; it takes effort, but you can see it through to a harvest.',
    ja: '{body}が{use}を剋し、体剋用。局面は自分の手中にあり、労は要るが最後は掌握して収穫できます。',
  },
  'liuyao.bodyUse.bodyFeedsUse': {
    en: '{body} generates {use} — 體生用. Your energy drains outward: much given, little returned. Leave yourself room and do not over-commit.',
    ja: '{body}が{use}を生じ、体生用。心力が外に漏れ、与える割に戻りが少ない。余地を残し、投入しすぎないこと。',
  },
  'liuyao.bodyUse.useOvercomesBody': {
    en: '{use} restrains {body} — 用剋體. Outside pressure exceeds your own force; forcing it now will only meet setbacks. Withdraw and wait for the timing.',
    ja: '{use}が{body}を剋し、用剋体。外圧が己身を上回り、今強いれば必ず挫かれます。退いて時を待ちましょう。',
  },

  // ── 文王卦（wenwang）──

  'wenwang.noUseGod': {
    en: '用神 does not appear in the hexagram and no 伏神 (hidden line) can be drawn on',
    ja: '用神が卦に現れず、伏神も取れません',
  },

  // ── 靈棋深度解讀（lingqiInterpretation）──
  // 上才（天時）、中才（人和）、下才（地利）是靈棋十二子固有的三才框架，
  // 譯文直接用 Heaven's timing／the human element／earthly standing 對應，
  // 不保留漢字——靈棋頁面沒有印著這幾個詞的盤面，沒有「對不起來」的問題。

  'lingqi.rank.upper.full': {
    en: 'Of the upper pieces (Heaven\'s timing), {n} face up — the timing is strong; the outer environment and the moment are the biggest variables in this matter.',
    ja: '上才（天時）{n} 子が表——天時が盛んで、外の環境とタイミングがこの件の最大の変数です。',
  },
  'lingqi.rank.upper.mid': {
    en: 'Of the upper pieces (Heaven\'s timing), {n} face up — the timing is middling; circumstances neither help nor hinder, and the outcome lies mostly in your own hands.',
    ja: '上才（天時）{n} 子が表——天時は中平。環境も時機も味方も敵もせず、成否は自分次第です。',
  },
  'lingqi.rank.upper.empty': {
    en: 'Not a single upper piece faces up — the timing has not come. Prepare quietly rather than pushing against the current.',
    ja: '上才（天時）はすべて伏す——時は未だ来ず。大勢に逆らわず、まず備えましょう。',
  },
  'lingqi.rank.middle.full': {
    en: 'Of the middle pieces (the human element), {n} face up — the human element is strong; the people around you and your own actions hold the key to this matter.',
    ja: '中才（人和）{n} 子が表——人和が盛んで、身近な人と自分の行いがこの件の鍵です。',
  },
  'lingqi.rank.middle.mid': {
    en: 'Of the middle pieces (the human element), {n} face up — help and hindrance are mixed; your own action is the deciding factor.',
    ja: '中才（人和）{n} 子が表——助力と妨げが半ばで、決め手は自分の行動です。',
  },
  'lingqi.rank.middle.empty': {
    en: 'Not a single middle piece faces up — outside help is scarce and you stand alone for now; steady what you can do by yourself first.',
    ja: '中才（人和）はすべて伏す——外の助けは頼りにくく、当面は孤軍。まず自分でできることを固めましょう。',
  },
  'lingqi.rank.lower.full': {
    en: 'Of the lower pieces (earthly standing), {n} face up — your foundation and resources hold firm; you can proceed with confidence.',
    ja: '下才（地利）{n} 子が表——地の利が盛んで、基盤と資源はしっかりしています。安心して進めます。',
  },
  'lingqi.rank.lower.mid': {
    en: 'Of the lower pieces (earthly standing), {n} face up — conditions are adequate; take stock of the resources in hand before acting.',
    ja: '下才（地利）{n} 子が表——条件はまずまず。動く前に手元の資源を棚卸ししましょう。',
  },
  'lingqi.rank.lower.empty': {
    en: 'Not a single lower piece faces up — the foundation is not yet firm; shore up your conditions before committing more.',
    ja: '下才（地利）はすべて伏す——基盤がまだ固まっていません。条件を整えてから加勢を。',
  },

  'lingqi.lead.upper': {
    en: 'This sign turns on Heaven\'s timing — read the outer environment and the moment first, and only then your own effort.',
    ja: 'この卦は天時を主軸に——まず外の環境とタイミングを読み、その後に自分の努力を論じます。',
  },
  'lingqi.lead.middle': {
    en: 'This sign turns on the human element — read yourself and the people around you first, and only then how favourable the circumstances are.',
    ja: 'この卦は人和を主軸に——まず自分と身近な人を読み、その後に環境の順逆を論じます。',
  },
  'lingqi.lead.lower': {
    en: 'This sign turns on earthly standing — read your foundation and resources first, and only then timing and connections.',
    ja: 'この卦は地利を主軸に——まず基盤と資源を読み、その後に時機と人脈を論じます。',
  },
  'lingqi.lead.tie.upperMiddle': {
    en: 'Heaven\'s timing and the human element are both strong — the outer environment and your own actions weigh equally; tend to both.',
    ja: '天時と人和が並んで盛ん——外の環境も自分の行いも同じ重さです。両方に目を配りましょう。',
  },
  'lingqi.lead.tie.upperLower': {
    en: 'Heaven\'s timing and earthly standing are both strong — the moment and the foundation are both in place; success now depends on action.',
    ja: '天時と地利が並んで盛ん——時機も基盤も整っています。成否は行動にかかっています。',
  },
  'lingqi.lead.tie.middleLower': {
    en: 'The human element and earthly standing are both strong — people and conditions are both ready; what is missing is putting them to use.',
    ja: '人和と地利が並んで盛ん——人も条件も揃っています。欠けているのはそれを使いこなすことです。',
  },
  'lingqi.lead.balanced': {
    en: 'The three powers are evenly matched and none dominates — inner and outer conditions are interwoven; read the whole picture rather than one side of it.',
    ja: '三才の数が揃い、際立つ才はありません——内外の条件が絡み合う事柄です。一面だけを見ず、全体で読みましょう。',
  },

  'lingqi.lens.marriage': {
    en: 'For a relationship question: hold the imagery of the Image against how you two are getting along now — which line sounds like them, and which like you.',
    ja: '恋愛の問い：象曰の意象を二人の今の関係に重ねてください——どの句が相手で、どの句が自分か。',
  },
  'lingqi.lens.career': {
    en: 'For a career question: hold the imagery of the Image against your current position and your next step — is this a sign of holding ground or of advancing?',
    ja: '仕事の問い：象曰の意象を今の立場と次の一手に重ねて——守りの象か、進みの象か。',
  },
  'lingqi.lens.wealth': {
    en: 'For a wealth question: hold the imagery of the Image against how money comes in and goes out — it can arrive and it can be kept; which link is missing?',
    ja: '金運の問い：象曰の意象をお金の入りと出に重ねて——入る・留まる、欠けているのはどちらか。',
  },
  'lingqi.lens.health': {
    en: 'For a health question: hold the imagery of the Image against the signs of body and mind and your daily rhythm — note the imbalance the text points to.',
    ja: '健康の問い：象曰の意象を心身の徴候と生活リズムに重ねて——文中が指す乱れに目を留めましょう。',
  },
  'lingqi.lens.study': {
    en: 'For a study question: hold the imagery of the Image against your stage and method of learning — is it the foundation or the method that is stuck?',
    ja: '学業の問い：象曰の意象を学びの段階と方法に重ねて——つまずいているのは基礎か方法か。',
  },
  'lingqi.lens.travel': {
    en: 'For a journey question: hold the imagery of the Image against how smoothly the trip may go — if the text shows signs of obstruction, prepare more before setting out.',
    ja: '旅行の問い：象曰の意象を道中の順逆に重ねて——文中に険しい象があれば、出発前に備えを。',
  },
  'lingqi.lens.general': {
    en: 'The question has no particular category: hold the imagery of the Image directly against the current state of the matter.',
    ja: '分類を定めない問い：象曰の意象を、事の現況にそのまま重ねてください。',
  },

  'lingqi.action.mirror': {
    en: 'Use the Image as a mirror: hold its imagery against the present state of the matter; do not force it word for word.',
    ja: '象を鏡に：象曰の意象を事の現況に重ね、一字一句に無理に当てはめないこと。',
  },
  'lingqi.action.focus.upper': {
    en: 'The timing is strongest: confirm the outer moment and conditions first, then decide the pace of your move.',
    ja: '天時が最も盛ん：まず外の時機と条件を確認してから、動くペースを決めましょう。',
  },
  'lingqi.action.focus.middle': {
    en: 'The human element is strongest: settle the people around you and your own state first; when relationships are in order, the matter follows.',
    ja: '人和が最も盛ん：まず身近な人と自分の状態を整えましょう。関係が整えば事も進みます。',
  },
  'lingqi.action.focus.lower': {
    en: 'Your standing is strongest: take stock of resources and foundation first, and shore up the conditions before acting.',
    ja: '地利が最も盛ん：まず資源と基盤を棚卸しし、条件を整えてから動きましょう。',
  },
  'lingqi.action.focus.tie': {
    en: 'Tied strengths weigh equally: start from whichever is closer to the present situation, and let the other follow.',
    ja: '並び立つ才は等しく重い：現況により近い一才から着手し、もう一才は後から追わせましょう。',
  },
  'lingqi.action.focus.balanced': {
    en: 'The three powers are even: begin with the step closest to daily life, and verify in small increments.',
    ja: '三才は均衡：日常生活に最も近い一歩から始め、小さく検証しましょう。',
  },
  'lingqi.action.verse': {
    en: 'Close with the Verse: it often points out where the matter is heading; treat it as a reference to check against, not as fate.',
    ja: '詩で締めくくる：詩曰は事の行方を指すことが多い。宿命ではなく、照合の参照として。',
  },
};
